2017-02-10 13:30:24 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "PLAY_EVOLUTIONS" not found; SQL statement:
select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%' [42102-191]
2017-03-29 15:50:39 database: wrong user or password; user: "X00126982"
org.h2.message.DbException: Wrong user name or password [28000-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:955)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-03-29 15:51:28 database: wrong user or password; user: "X00126982"
org.h2.message.DbException: Wrong user name or password [28000-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:955)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-04-03 12:57:25 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-03 12:57:25 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-03 19:26:19 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-04-11 16:07:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-11 16:07:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-19 13:27:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-19 13:27:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-19 14:16:14 jdbc[215]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-04-19 15:46:19 jdbc[326]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-04-19 17:08:55 jdbc[16]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-04-19 18:20:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-19 18:20:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-20 20:04:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'14.00' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-20 20:04:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'14.00' (PRODUCT: STOCK INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."PRODUCT"("ID","NAME","DESCRIPTION","STOCK","PRICE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-191]
2017-04-20 20:57:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 20:57:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 20:58:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 20:58:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 20:58:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 20:58:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 20:59:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 20:59:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 21:01:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-20 21:01:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CATEGORY_PRODUCT: CATEGORY_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CATEGORY_PRODUCT"("CATEGORY_ID","PRODUCT_ID")VALUES(?,?) -- (?1, ?2) [22018-191]
2017-04-24 18:29:40 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
